name: OpenWrt-CI

on:
  push:
    branches: 
      - master

jobs:
  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q) || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get update
          sudo -E apt-get -y install \
            build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev \
            libz-dev patch python3 unzip zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 \
            subversion flex bison uglifyjs msmtp libglib2.0-dev xmlto qemu-utils upx-ucl \
            libssl-dev texinfo autopoint device-tree-compiler gperf libtinfo5 libelf-dev
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          df -h

      - name: Update feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate configuration
        run: |
          cp $GITHUB_WORKSPACE/config.cm520 .config
          make defconfig

      - name: Apply DTS Patch
        run: |
          bash $GITHUB_WORKSPACE/config.sh && PATCH_DTS

      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware
          path: ./bin/targets/
